@extends('layouts.admin')
@section('page-title', 'Show Return Request')
@section('content')
<div class="admin-page-head"><div><a href="{{ route('admin.return-requests.index') }}" class="admin-back-link">&larr; {{ trans('global.back_to_list') }}</a><h2 class="admin-page-title">Return Request Details</h2><p class="admin-page-subtitle">Return item snapshot and approval workflow</p></div><div class="show-actions">@can('return_request_edit')<a href="{{ route('admin.return-requests.edit',$returnRequest->id) }}" class="btn-primary"><i class="fas fa-pencil-alt"></i> Edit Return Request</a>@endcan <a href="{{ route('admin.return-requests.index') }}" class="btn-outline"><i class="fas fa-list"></i> Back to list</a>@can('return_request_delete')<form action="{{ route('admin.return-requests.destroy',$returnRequest->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}')">@method('DELETE')@csrf<button class="btn-danger"><i class="fas fa-trash-alt"></i> Delete Return Request</button></form>@endcan</div></div>
<div class="show-grid"><div><div class="detail-card mb-3"><div class="profile-hero"><div class="profile-avatar-lg" style="background:#4F46E5;"><i class="fas fa-undo-alt"></i></div><p class="profile-title">{{ $returnRequest->return_number }}</p><p class="profile-subtitle">{{ optional($returnRequest->order)->order_number ?: '-' }}</p><span class="status-pill {{ in_array($returnRequest->status,['approved','picked_up','refunded']) ? 'success' : 'warning' }}">{{ \App\Models\ReturnRequest::STATUSES[$returnRequest->status] ?? $returnRequest->status }}</span></div><div class="detail-section-pad-sm"><div class="stat-mini"><p class="stat-mini-label">Refund Amount</p><p class="stat-mini-value">Rs. {{ number_format($returnRequest->refund_amount,2) }}</p></div><div class="stat-mini"><p class="stat-mini-label">Requested At</p><p class="stat-mini-value-sm">{{ optional($returnRequest->requested_at)->format('d M Y, H:i') ?: '-' }}</p></div></div></div></div>
<div><div class="detail-card mb-3"><div class="detail-section-head"><div class="detail-section-icon"><i class="fas fa-info"></i></div><p class="detail-section-title">Return Information</p></div><div class="detail-section-body"><div class="detail-row"><span class="detail-label">Order</span><span class="detail-value">{{ optional($returnRequest->order)->order_number ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Reason</span><span class="detail-value">{{ $returnRequest->reason ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Description</span><span class="detail-value">{{ $returnRequest->description ?: '-' }}</span></div></div></div>
<div class="detail-card mb-3"><div class="detail-section-head"><div class="detail-section-icon"><i class="fas fa-user"></i></div><p class="detail-section-title">Customer & Shop</p></div><div class="detail-section-body"><div class="detail-row"><span class="detail-label">Customer</span><span class="detail-value">{{ optional($returnRequest->customer)->name ?: optional($returnRequest->order)->customer_name ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Shop</span><span class="detail-value">{{ optional($returnRequest->shop)->shop_name ?: '-' }}</span></div></div></div>
<div class="detail-card mb-3"><div class="detail-section-head"><div class="detail-section-icon"><i class="fas fa-tshirt"></i></div><p class="detail-section-title">Product Item Snapshot</p></div><div class="detail-section-body"><div class="detail-row"><span class="detail-label">Product</span><span class="detail-value">{{ $returnRequest->product_name ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Size/Color</span><span class="detail-value">{{ $returnRequest->size ?: '-' }} / {{ $returnRequest->color ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Qty</span><span class="detail-value">{{ $returnRequest->quantity }}</span></div><div class="detail-row"><span class="detail-label">Price</span><span class="detail-value">Rs. {{ number_format($returnRequest->price,2) }}</span></div></div></div>
@can('return_request_status_update')<div class="detail-card mb-3"><div class="detail-section-head"><div class="detail-section-icon"><i class="fas fa-sliders-h"></i></div><p class="detail-section-title">Status Update Form</p></div><div class="detail-section-body"><form method="POST" action="{{ route('admin.return-requests.updateStatus',$returnRequest->id) }}">@csrf<div class="field-group"><select name="status" class="field-input">@foreach(\App\Models\ReturnRequest::STATUSES as $value=>$label)<option value="{{ $value }}" {{ $returnRequest->status === $value ? 'selected' : '' }}>{{ $label }}</option>@endforeach</select></div><div class="field-group"><textarea name="admin_note" rows="3" class="field-input" placeholder="Admin note">{{ $returnRequest->admin_note }}</textarea></div><button class="btn-primary"><i class="fas fa-save"></i> Update Status</button></form></div></div>@endcan
<div class="detail-card"><div class="detail-section-head"><div class="detail-section-icon"><i class="fas fa-sticky-note"></i></div><p class="detail-section-title">Admin Note</p></div><div class="detail-section-body"><div class="detail-row"><span class="detail-label">Note</span><span class="detail-value">{{ $returnRequest->admin_note ?: '-' }}</span></div></div></div></div></div>
@endsection
