@extends('layouts.admin')
@section('page-title','Show Receipt')
@section('content')
<div class="admin-page-head"><div><a href="{{ route('admin.receipts.index') }}" class="admin-back-link">&larr; {{ trans('global.back_to_list') }}</a><h2 class="admin-page-title">Receipt Details</h2><p class="admin-page-subtitle">Payment receipt snapshot and references</p></div><div class="show-actions">@can('receipt_edit')<a href="{{ route('admin.receipts.edit',$receipt->id) }}" class="btn-primary"><i class="fas fa-pencil-alt"></i> Edit Receipt</a>@endcan @can('receipt_print')<a href="{{ route('admin.receipts.print',$receipt->id) }}" class="btn-outline"><i class="fas fa-print"></i> Print Receipt</a>@endcan <a href="{{ route('admin.receipts.index') }}" class="btn-outline"><i class="fas fa-list"></i> Back to list</a>@can('receipt_delete')<form action="{{ route('admin.receipts.destroy',$receipt->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}')">@method('DELETE')@csrf<button class="btn-danger"><i class="fas fa-trash-alt"></i> Delete Receipt</button></form>@endcan</div></div>
<div class="show-grid"><div><div class="detail-card mb-3"><div class="profile-hero"><div class="profile-avatar-lg" style="background:#4F46E5;"><i class="fas fa-receipt"></i></div><p class="profile-title">{{ $receipt->receipt_number }}</p><p class="profile-subtitle">{{ \App\Models\Receipt::TYPES[$receipt->receipt_type] ?? $receipt->receipt_type }} / {{ strtoupper($receipt->payment_method ?: '-') }}</p><span class="status-pill {{ $receipt->status === 'paid' ? 'success' : 'warning' }}">{{ \App\Models\Receipt::STATUSES[$receipt->status] ?? $receipt->status }}</span></div><div class="detail-section-pad-sm"><div class="stat-mini"><p class="stat-mini-label">Amount</p><p class="stat-mini-value">Rs. {{ number_format($receipt->amount,2) }}</p></div></div></div></div>
<div><div class="detail-card mb-3"><div class="detail-section-head"><div class="detail-section-icon"><i class="fas fa-info"></i></div><p class="detail-section-title">Receipt Information</p></div><div class="detail-section-body"><div class="detail-row"><span class="detail-label">Receipt Date</span><span class="detail-value">{{ optional($receipt->receipt_date)->format('d M Y') ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Type</span><span class="detail-value">{{ \App\Models\Receipt::TYPES[$receipt->receipt_type] ?? $receipt->receipt_type }}</span></div><div class="detail-row"><span class="detail-label">Status</span><span class="detail-value">{{ $receipt->status }}</span></div></div></div>
<div class="detail-card mb-3"><div class="detail-section-head"><div class="detail-section-icon"><i class="fas fa-link"></i></div><p class="detail-section-title">Order/Invoice Reference</p></div><div class="detail-section-body"><div class="detail-row"><span class="detail-label">Order</span><span class="detail-value">{{ optional($receipt->order)->order_number ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Invoice</span><span class="detail-value">{{ optional($receipt->invoice)->invoice_number ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Payment</span><span class="detail-value">#{{ $receipt->payment_id ?: '-' }}</span></div></div></div>
<div class="detail-card mb-3"><div class="detail-section-head"><div class="detail-section-icon"><i class="fas fa-user"></i></div><p class="detail-section-title">Customer & Shop</p></div><div class="detail-section-body"><div class="detail-row"><span class="detail-label">Customer</span><span class="detail-value">{{ optional($receipt->customer)->name ?: optional($receipt->order)->customer_name ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Shop</span><span class="detail-value">{{ optional($receipt->shop)->shop_name ?: '-' }}</span></div></div></div>
<div class="detail-card mb-3"><div class="detail-section-head"><div class="detail-section-icon"><i class="fas fa-wallet"></i></div><p class="detail-section-title">Payment/Gateway Details</p></div><div class="detail-section-body"><div class="detail-row"><span class="detail-label">Method</span><span class="detail-value">{{ $receipt->payment_method ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Gateway</span><span class="detail-value">{{ $receipt->payment_gateway ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Transaction ID</span><span class="detail-value code-pill">{{ $receipt->transaction_id ?: '-' }}</span></div></div></div>
<div class="detail-card"><div class="detail-section-head"><div class="detail-section-icon"><i class="fas fa-sticky-note"></i></div><p class="detail-section-title">Notes</p></div><div class="detail-section-body"><div class="detail-row"><span class="detail-label">Received From</span><span class="detail-value">{{ $receipt->received_from ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Received By</span><span class="detail-value">{{ $receipt->received_by ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Notes</span><span class="detail-value">{{ $receipt->notes ?: '-' }}</span></div><div class="detail-row"><span class="detail-label">Admin Note</span><span class="detail-value">{{ $receipt->admin_note ?: '-' }}</span></div></div></div></div></div>
@endsection
