<div class="form-card"><div class="form-card-header"><div class="form-card-icon"><i class="fas fa-receipt"></i></div><div><p class="form-card-title">Receipt Reference</p><p class="form-card-subtitle">Invoice, order, payment and customer mapping</p></div></div><div class="form-card-body">
<div class="field-group"><label class="field-label">Invoice</label><select name="invoice_id" class="field-input">@foreach($invoices as $id=>$entry)<option value="{{ $id }}" {{ (string) old('invoice_id', optional($receipt)->invoice_id) === (string) $id ? 'selected' : '' }}>{{ $entry }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Order</label><select name="order_id" class="field-input">@foreach($orders as $id=>$entry)<option value="{{ $id }}" {{ (string) old('order_id', optional($receipt)->order_id) === (string) $id ? 'selected' : '' }}>{{ $entry }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Payment</label><select name="payment_id" class="field-input">@foreach($payments as $id=>$entry)<option value="{{ $id }}" {{ (string) old('payment_id', optional($receipt)->payment_id) === (string) $id ? 'selected' : '' }}>{{ $entry }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Customer</label><select name="customer_id" class="field-input">@foreach($customers as $id=>$entry)<option value="{{ $id }}" {{ (string) old('customer_id', optional($receipt)->customer_id) === (string) $id ? 'selected' : '' }}>{{ $entry }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Shop</label><select name="shop_id" class="field-input">@foreach($shops as $id=>$entry)<option value="{{ $id }}" {{ (string) old('shop_id', optional($receipt)->shop_id) === (string) $id ? 'selected' : '' }}>{{ $entry }}</option>@endforeach</select></div>
</div></div>
<div class="form-card"><div class="form-card-header"><div class="form-card-icon"><i class="fas fa-wallet"></i></div><div><p class="form-card-title">Payment Details</p><p class="form-card-subtitle">Receipt amount and transaction details</p></div></div><div class="form-card-body">
<div class="field-group"><label class="field-label">Receipt Type</label><select name="receipt_type" class="field-input">@foreach(\App\Models\Receipt::TYPES as $value=>$label)<option value="{{ $value }}" {{ old('receipt_type', optional($receipt)->receipt_type ?: 'payment') === $value ? 'selected' : '' }}>{{ $label }}</option>@endforeach</select></div>
<div class="field-group"><label class="field-label">Receipt Date</label><input type="date" name="receipt_date" value="{{ old('receipt_date', optional(optional($receipt)->receipt_date)->format('Y-m-d')) }}" class="field-input"></div>
<div class="field-group"><label class="field-label">Payment Method</label><input name="payment_method" value="{{ old('payment_method', optional($receipt)->payment_method) }}" class="field-input"></div>
<div class="field-group"><label class="field-label">Payment Gateway</label><input name="payment_gateway" value="{{ old('payment_gateway', optional($receipt)->payment_gateway) }}" class="field-input"></div>
<div class="field-group"><label class="field-label">Transaction ID</label><input name="transaction_id" value="{{ old('transaction_id', optional($receipt)->transaction_id) }}" class="field-input"></div>
<div class="field-group"><label class="field-label">Amount</label><input type="number" step="0.01" min="0" name="amount" value="{{ old('amount', optional($receipt)->amount ?? 0) }}" required class="field-input"></div>
<div class="field-group"><label class="field-label">Status</label><select name="status" class="field-input">@foreach(\App\Models\Receipt::STATUSES as $value=>$label)<option value="{{ $value }}" {{ old('status', optional($receipt)->status ?: 'paid') === $value ? 'selected' : '' }}>{{ $label }}</option>@endforeach</select></div>
</div></div>
<div class="form-card"><div class="form-card-header"><div class="form-card-icon"><i class="fas fa-sticky-note"></i></div><div><p class="form-card-title">Receiver & Notes</p><p class="form-card-subtitle">Received from/by and notes</p></div></div><div class="form-card-body">
<div class="field-group"><label class="field-label">Received From</label><input name="received_from" value="{{ old('received_from', optional($receipt)->received_from) }}" class="field-input"></div>
<div class="field-group"><label class="field-label">Received By</label><input name="received_by" value="{{ old('received_by', optional($receipt)->received_by) }}" class="field-input"></div>
<div class="field-group"><label class="field-label">Notes</label><textarea name="notes" rows="3" class="field-input">{{ old('notes', optional($receipt)->notes) }}</textarea></div>
<div class="field-group"><label class="field-label">Admin Note</label><textarea name="admin_note" rows="3" class="field-input">{{ old('admin_note', optional($receipt)->admin_note) }}</textarea></div>
</div></div>
